package com.github.pigsteel.smcm.util;

import net.minecraft.world.entity.AreaEffectCloud;
import net.minecraft.world.entity.Display;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ExperienceOrb;
import net.minecraft.world.entity.Interaction;
import net.minecraft.world.entity.LightningBolt;
import net.minecraft.world.entity.Marker;
import net.minecraft.world.entity.OminousItemSpawner;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.armadillo.Armadillo;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.bee.Bee;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.camel.CamelHusk;
import net.minecraft.world.entity.animal.chicken.Chicken;
import net.minecraft.world.entity.animal.cow.Cow;
import net.minecraft.world.entity.animal.cow.MushroomCow;
import net.minecraft.world.entity.animal.dolphin.Dolphin;
import net.minecraft.world.entity.animal.equine.Donkey;
import net.minecraft.world.entity.animal.equine.Horse;
import net.minecraft.world.entity.animal.equine.Llama;
import net.minecraft.world.entity.animal.equine.Mule;
import net.minecraft.world.entity.animal.equine.SkeletonHorse;
import net.minecraft.world.entity.animal.equine.TraderLlama;
import net.minecraft.world.entity.animal.equine.ZombieHorse;
import net.minecraft.world.entity.animal.feline.Cat;
import net.minecraft.world.entity.animal.feline.Ocelot;
import net.minecraft.world.entity.animal.fish.Cod;
import net.minecraft.world.entity.animal.fish.Pufferfish;
import net.minecraft.world.entity.animal.fish.Salmon;
import net.minecraft.world.entity.animal.fish.TropicalFish;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.golem.CopperGolem;
import net.minecraft.world.entity.animal.golem.IronGolem;
import net.minecraft.world.entity.animal.golem.SnowGolem;
import net.minecraft.world.entity.animal.happyghast.HappyGhast;
import net.minecraft.world.entity.animal.nautilus.Nautilus;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilus;
import net.minecraft.world.entity.animal.panda.Panda;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.animal.pig.Pig;
import net.minecraft.world.entity.animal.polarbear.PolarBear;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.animal.squid.GlowSquid;
import net.minecraft.world.entity.animal.squid.Squid;
import net.minecraft.world.entity.animal.turtle.Turtle;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.decoration.GlowItemFrame;
import net.minecraft.world.entity.decoration.ItemFrame;
import net.minecraft.world.entity.decoration.LeashFenceKnotEntity;
import net.minecraft.world.entity.decoration.Mannequin;
import net.minecraft.world.entity.decoration.painting.Painting;
import net.minecraft.world.entity.item.FallingBlockEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.item.PrimedTnt;
import net.minecraft.world.entity.monster.Blaze;
import net.minecraft.world.entity.monster.Creeper;
import net.minecraft.world.entity.monster.ElderGuardian;
import net.minecraft.world.entity.monster.EnderMan;
import net.minecraft.world.entity.monster.Endermite;
import net.minecraft.world.entity.monster.Ghast;
import net.minecraft.world.entity.monster.Giant;
import net.minecraft.world.entity.monster.Guardian;
//? <26.2 {
/*import net.minecraft.world.entity.monster.MagmaCube;
import net.minecraft.world.entity.monster.Slime;
*///?} >= 26.2 {
import net.minecraft.world.entity.monster.cubemob.MagmaCube;
import net.minecraft.world.entity.monster.cubemob.Slime;
//?}
import net.minecraft.world.entity.monster.Phantom;
import net.minecraft.world.entity.monster.Ravager;
import net.minecraft.world.entity.monster.Shulker;
import net.minecraft.world.entity.monster.Silverfish;
import net.minecraft.world.entity.monster.Strider;
import net.minecraft.world.entity.monster.Vex;
import net.minecraft.world.entity.monster.Witch;
import net.minecraft.world.entity.monster.Zoglin;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.illager.Evoker;
import net.minecraft.world.entity.monster.illager.Illusioner;
import net.minecraft.world.entity.monster.illager.Pillager;
import net.minecraft.world.entity.monster.illager.Vindicator;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.monster.skeleton.Bogged;
import net.minecraft.world.entity.monster.skeleton.Parched;
import net.minecraft.world.entity.monster.skeleton.Skeleton;
import net.minecraft.world.entity.monster.skeleton.Stray;
import net.minecraft.world.entity.monster.skeleton.WitherSkeleton;
import net.minecraft.world.entity.monster.spider.CaveSpider;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.monster.zombie.Drowned;
import net.minecraft.world.entity.monster.zombie.Husk;
import net.minecraft.world.entity.monster.zombie.Zombie;
import net.minecraft.world.entity.monster.zombie.ZombieVillager;
import net.minecraft.world.entity.monster.zombie.ZombifiedPiglin;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.npc.wanderingtrader.WanderingTrader;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.entity.projectile.EvokerFangs;
import net.minecraft.world.entity.projectile.EyeOfEnder;
import net.minecraft.world.entity.projectile.FireworkRocketEntity;
import net.minecraft.world.entity.projectile.FishingHook;
import net.minecraft.world.entity.projectile.LlamaSpit;
import net.minecraft.world.entity.projectile.ShulkerBullet;
import net.minecraft.world.entity.projectile.arrow.Arrow;
import net.minecraft.world.entity.projectile.arrow.SpectralArrow;
import net.minecraft.world.entity.projectile.arrow.ThrownTrident;
import net.minecraft.world.entity.projectile.hurtingprojectile.DragonFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.LargeFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.SmallFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.WitherSkull;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.BreezeWindCharge;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.WindCharge;
import net.minecraft.world.entity.projectile.throwableitemprojectile.Snowball;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownEgg;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownEnderpearl;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownExperienceBottle;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownLingeringPotion;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownSplashPotion;
import net.minecraft.world.entity.vehicle.boat.Boat;
import net.minecraft.world.entity.vehicle.boat.ChestBoat;
import net.minecraft.world.entity.vehicle.boat.ChestRaft;
import net.minecraft.world.entity.vehicle.boat.Raft;
import net.minecraft.world.entity.vehicle.minecart.Minecart;
import net.minecraft.world.entity.vehicle.minecart.MinecartChest;
import net.minecraft.world.entity.vehicle.minecart.MinecartCommandBlock;
import net.minecraft.world.entity.vehicle.minecart.MinecartFurnace;
import net.minecraft.world.entity.vehicle.minecart.MinecartHopper;
import net.minecraft.world.entity.vehicle.minecart.MinecartSpawner;
import net.minecraft.world.entity.vehicle.minecart.MinecartTNT;

//? >=26.2 {
import net.minecraft.world.entity.EntityTypes;
//?}

public class EntityTypesUtil {
	private EntityTypesUtil() {
	}

	public static final EntityType<Boat> ACACIA_BOAT;
	public static final EntityType<ChestBoat> ACACIA_CHEST_BOAT;
	public static final EntityType<Allay> ALLAY;
	public static final EntityType<AreaEffectCloud> AREA_EFFECT_CLOUD;
	public static final EntityType<Armadillo> ARMADILLO;
	public static final EntityType<ArmorStand> ARMOR_STAND;
	public static final EntityType<Arrow> ARROW;
	public static final EntityType<Axolotl> AXOLOTL;
	public static final EntityType<ChestRaft> BAMBOO_CHEST_RAFT;
	public static final EntityType<Raft> BAMBOO_RAFT;
	public static final EntityType<Bat> BAT;
	public static final EntityType<Bee> BEE;
	public static final EntityType<Boat> BIRCH_BOAT;
	public static final EntityType<ChestBoat> BIRCH_CHEST_BOAT;
	public static final EntityType<Blaze> BLAZE;
	public static final EntityType<Display.BlockDisplay> BLOCK_DISPLAY;
	public static final EntityType<Bogged> BOGGED;
	public static final EntityType<Breeze> BREEZE;
	public static final EntityType<BreezeWindCharge> BREEZE_WIND_CHARGE;
	public static final EntityType<Camel> CAMEL;
	public static final EntityType<CamelHusk> CAMEL_HUSK;
	public static final EntityType<Cat> CAT;
	public static final EntityType<CaveSpider> CAVE_SPIDER;
	public static final EntityType<Boat> CHERRY_BOAT;
	public static final EntityType<ChestBoat> CHERRY_CHEST_BOAT;
	public static final EntityType<MinecartChest> CHEST_MINECART;
	public static final EntityType<Chicken> CHICKEN;
	public static final EntityType<Cod> COD;
	public static final EntityType<CopperGolem> COPPER_GOLEM;
	public static final EntityType<MinecartCommandBlock> COMMAND_BLOCK_MINECART;
	public static final EntityType<Cow> COW;
	public static final EntityType<Creaking> CREAKING;
	public static final EntityType<Creeper> CREEPER;
	public static final EntityType<Boat> DARK_OAK_BOAT;
	public static final EntityType<ChestBoat> DARK_OAK_CHEST_BOAT;
	public static final EntityType<Dolphin> DOLPHIN;
	public static final EntityType<Donkey> DONKEY;
	public static final EntityType<DragonFireball> DRAGON_FIREBALL;
	public static final EntityType<Drowned> DROWNED;
	public static final EntityType<ThrownEgg> EGG;
	public static final EntityType<ElderGuardian> ELDER_GUARDIAN;
	public static final EntityType<EnderMan> ENDERMAN;
	public static final EntityType<Endermite> ENDERMITE;
	public static final EntityType<EnderDragon> ENDER_DRAGON;
	public static final EntityType<ThrownEnderpearl> ENDER_PEARL;
	public static final EntityType<EndCrystal> END_CRYSTAL;
	public static final EntityType<Evoker> EVOKER;
	public static final EntityType<EvokerFangs> EVOKER_FANGS;
	public static final EntityType<ThrownExperienceBottle> EXPERIENCE_BOTTLE;
	public static final EntityType<ExperienceOrb> EXPERIENCE_ORB;
	public static final EntityType<EyeOfEnder> EYE_OF_ENDER;
	public static final EntityType<FallingBlockEntity> FALLING_BLOCK;
	public static final EntityType<LargeFireball> FIREBALL;
	public static final EntityType<FireworkRocketEntity> FIREWORK_ROCKET;
	public static final EntityType<Fox> FOX;
	public static final EntityType<Frog> FROG;
	public static final EntityType<MinecartFurnace> FURNACE_MINECART;
	public static final EntityType<Ghast> GHAST;
	public static final EntityType<HappyGhast> HAPPY_GHAST;
	public static final EntityType<Giant> GIANT;
	public static final EntityType<GlowItemFrame> GLOW_ITEM_FRAME;
	public static final EntityType<GlowSquid> GLOW_SQUID;
	public static final EntityType<Goat> GOAT;
	public static final EntityType<Guardian> GUARDIAN;
	public static final EntityType<Hoglin> HOGLIN;
	public static final EntityType<MinecartHopper> HOPPER_MINECART;
	public static final EntityType<Horse> HORSE;
	public static final EntityType<Husk> HUSK;
	public static final EntityType<Illusioner> ILLUSIONER;
	public static final EntityType<Interaction> INTERACTION;
	public static final EntityType<IronGolem> IRON_GOLEM;
	public static final EntityType<ItemEntity> ITEM;
	public static final EntityType<Display.ItemDisplay> ITEM_DISPLAY;
	public static final EntityType<ItemFrame> ITEM_FRAME;
	public static final EntityType<Boat> JUNGLE_BOAT;
	public static final EntityType<ChestBoat> JUNGLE_CHEST_BOAT;
	public static final EntityType<LeashFenceKnotEntity> LEASH_KNOT;
	public static final EntityType<LightningBolt> LIGHTNING_BOLT;
	public static final EntityType<Llama> LLAMA;
	public static final EntityType<LlamaSpit> LLAMA_SPIT;
	public static final EntityType<MagmaCube> MAGMA_CUBE;
	public static final EntityType<Boat> MANGROVE_BOAT;
	public static final EntityType<ChestBoat> MANGROVE_CHEST_BOAT;
	public static final EntityType<Mannequin> MANNEQUIN;
	public static final EntityType<Marker> MARKER;
	public static final EntityType<Minecart> MINECART;
	public static final EntityType<MushroomCow> MOOSHROOM;
	public static final EntityType<Mule> MULE;
	public static final EntityType<Nautilus> NAUTILUS;
	public static final EntityType<Boat> OAK_BOAT;
	public static final EntityType<ChestBoat> OAK_CHEST_BOAT;
	public static final EntityType<Ocelot> OCELOT;
	public static final EntityType<OminousItemSpawner> OMINOUS_ITEM_SPAWNER;
	public static final EntityType<Painting> PAINTING;
	public static final EntityType<Boat> PALE_OAK_BOAT;
	public static final EntityType<ChestBoat> PALE_OAK_CHEST_BOAT;
	public static final EntityType<Panda> PANDA;
	public static final EntityType<Parched> PARCHED;
	public static final EntityType<Parrot> PARROT;
	public static final EntityType<Phantom> PHANTOM;
	public static final EntityType<Pig> PIG;
	public static final EntityType<Piglin> PIGLIN;
	public static final EntityType<PiglinBrute> PIGLIN_BRUTE;
	public static final EntityType<Pillager> PILLAGER;
	public static final EntityType<PolarBear> POLAR_BEAR;
	public static final EntityType<ThrownSplashPotion> SPLASH_POTION;
	public static final EntityType<ThrownLingeringPotion> LINGERING_POTION;
	public static final EntityType<Pufferfish> PUFFERFISH;
	public static final EntityType<Rabbit> RABBIT;
	public static final EntityType<Ravager> RAVAGER;
	public static final EntityType<Salmon> SALMON;
	public static final EntityType<Sheep> SHEEP;
	public static final EntityType<Shulker> SHULKER;
	public static final EntityType<ShulkerBullet> SHULKER_BULLET;
	public static final EntityType<Silverfish> SILVERFISH;
	public static final EntityType<Skeleton> SKELETON;
	public static final EntityType<SkeletonHorse> SKELETON_HORSE;
	public static final EntityType<Slime> SLIME;
	public static final EntityType<SmallFireball> SMALL_FIREBALL;
	public static final EntityType<Sniffer> SNIFFER;
	public static final EntityType<Snowball> SNOWBALL;
	public static final EntityType<SnowGolem> SNOW_GOLEM;
	public static final EntityType<MinecartSpawner> SPAWNER_MINECART;
	public static final EntityType<SpectralArrow> SPECTRAL_ARROW;
	public static final EntityType<Spider> SPIDER;
	public static final EntityType<Boat> SPRUCE_BOAT;
	public static final EntityType<ChestBoat> SPRUCE_CHEST_BOAT;
	public static final EntityType<Squid> SQUID;
	public static final EntityType<Stray> STRAY;
	public static final EntityType<Strider> STRIDER;
	public static final EntityType<Tadpole> TADPOLE;
	public static final EntityType<Display.TextDisplay> TEXT_DISPLAY;
	public static final EntityType<PrimedTnt> TNT;
	public static final EntityType<MinecartTNT> TNT_MINECART;
	public static final EntityType<TraderLlama> TRADER_LLAMA;
	public static final EntityType<ThrownTrident> TRIDENT;
	public static final EntityType<TropicalFish> TROPICAL_FISH;
	public static final EntityType<Turtle> TURTLE;
	public static final EntityType<Vex> VEX;
	public static final EntityType<Villager> VILLAGER;
	public static final EntityType<Vindicator> VINDICATOR;
	public static final EntityType<WanderingTrader> WANDERING_TRADER;
	public static final EntityType<Warden> WARDEN;
	public static final EntityType<WindCharge> WIND_CHARGE;
	public static final EntityType<Witch> WITCH;
	public static final EntityType<WitherBoss> WITHER;
	public static final EntityType<WitherSkeleton> WITHER_SKELETON;
	public static final EntityType<WitherSkull> WITHER_SKULL;
	public static final EntityType<Wolf> WOLF;
	public static final EntityType<Zoglin> ZOGLIN;
	public static final EntityType<Zombie> ZOMBIE;
	public static final EntityType<ZombieHorse> ZOMBIE_HORSE;
	public static final EntityType<ZombieNautilus> ZOMBIE_NAUTILUS;
	public static final EntityType<ZombieVillager> ZOMBIE_VILLAGER;
	public static final EntityType<ZombifiedPiglin> ZOMBIFIED_PIGLIN;
	public static final EntityType<Player> PLAYER;
	public static final EntityType<FishingHook> FISHING_BOBBER;

	static {
		//? <26.2 {
		/*ACACIA_BOAT = EntityType.ACACIA_BOAT;
		ACACIA_CHEST_BOAT = EntityType.ACACIA_CHEST_BOAT;
		ALLAY = EntityType.ALLAY;
		AREA_EFFECT_CLOUD = EntityType.AREA_EFFECT_CLOUD;
		ARMADILLO = EntityType.ARMADILLO;
		ARMOR_STAND = EntityType.ARMOR_STAND;
		ARROW = EntityType.ARROW;
		AXOLOTL = EntityType.AXOLOTL;
		BAMBOO_CHEST_RAFT = EntityType.BAMBOO_CHEST_RAFT;
		BAMBOO_RAFT = EntityType.BAMBOO_RAFT;
		BAT = EntityType.BAT;
		BEE = EntityType.BEE;
		BIRCH_BOAT = EntityType.BIRCH_BOAT;
		BIRCH_CHEST_BOAT = EntityType.BIRCH_CHEST_BOAT;
		BLAZE = EntityType.BLAZE;
		BLOCK_DISPLAY = EntityType.BLOCK_DISPLAY;
		BOGGED = EntityType.BOGGED;
		BREEZE = EntityType.BREEZE;
		BREEZE_WIND_CHARGE = EntityType.BREEZE_WIND_CHARGE;
		CAMEL = EntityType.CAMEL;
		CAMEL_HUSK = EntityType.CAMEL_HUSK;
		CAT = EntityType.CAT;
		CAVE_SPIDER = EntityType.CAVE_SPIDER;
		CHERRY_BOAT = EntityType.CHERRY_BOAT;
		CHERRY_CHEST_BOAT = EntityType.CHERRY_CHEST_BOAT;
		CHEST_MINECART = EntityType.CHEST_MINECART;
		CHICKEN = EntityType.CHICKEN;
		COD = EntityType.COD;
		COPPER_GOLEM = EntityType.COPPER_GOLEM;
		COMMAND_BLOCK_MINECART = EntityType.COMMAND_BLOCK_MINECART;
		COW = EntityType.COW;
		CREAKING = EntityType.CREAKING;
		CREEPER = EntityType.CREEPER;
		DARK_OAK_BOAT = EntityType.DARK_OAK_BOAT;
		DARK_OAK_CHEST_BOAT = EntityType.DARK_OAK_CHEST_BOAT;
		DOLPHIN = EntityType.DOLPHIN;
		DONKEY = EntityType.DONKEY;
		DRAGON_FIREBALL = EntityType.DRAGON_FIREBALL;
		DROWNED = EntityType.DROWNED;
		EGG = EntityType.EGG;
		ELDER_GUARDIAN = EntityType.ELDER_GUARDIAN;
		ENDERMAN = EntityType.ENDERMAN;
		ENDERMITE = EntityType.ENDERMITE;
		ENDER_DRAGON = EntityType.ENDER_DRAGON;
		ENDER_PEARL = EntityType.ENDER_PEARL;
		END_CRYSTAL = EntityType.END_CRYSTAL;
		EVOKER = EntityType.EVOKER;
		EVOKER_FANGS = EntityType.EVOKER_FANGS;
		EXPERIENCE_BOTTLE = EntityType.EXPERIENCE_BOTTLE;
		EXPERIENCE_ORB = EntityType.EXPERIENCE_ORB;
		EYE_OF_ENDER = EntityType.EYE_OF_ENDER;
		FALLING_BLOCK = EntityType.FALLING_BLOCK;
		FIREBALL = EntityType.FIREBALL;
		FIREWORK_ROCKET = EntityType.FIREWORK_ROCKET;
		FOX = EntityType.FOX;
		FROG = EntityType.FROG;
		FURNACE_MINECART = EntityType.FURNACE_MINECART;
		GHAST = EntityType.GHAST;
		HAPPY_GHAST = EntityType.HAPPY_GHAST;
		GIANT = EntityType.GIANT;
		GLOW_ITEM_FRAME = EntityType.GLOW_ITEM_FRAME;
		GLOW_SQUID = EntityType.GLOW_SQUID;
		GOAT = EntityType.GOAT;
		GUARDIAN = EntityType.GUARDIAN;
		HOGLIN = EntityType.HOGLIN;
		HOPPER_MINECART = EntityType.HOPPER_MINECART;
		HORSE = EntityType.HORSE;
		HUSK = EntityType.HUSK;
		ILLUSIONER = EntityType.ILLUSIONER;
		INTERACTION = EntityType.INTERACTION;
		IRON_GOLEM = EntityType.IRON_GOLEM;
		ITEM = EntityType.ITEM;
		ITEM_DISPLAY = EntityType.ITEM_DISPLAY;
		ITEM_FRAME = EntityType.ITEM_FRAME;
		JUNGLE_BOAT = EntityType.JUNGLE_BOAT;
		JUNGLE_CHEST_BOAT = EntityType.JUNGLE_CHEST_BOAT;
		LEASH_KNOT = EntityType.LEASH_KNOT;
		LIGHTNING_BOLT = EntityType.LIGHTNING_BOLT;
		LLAMA = EntityType.LLAMA;
		LLAMA_SPIT = EntityType.LLAMA_SPIT;
		MAGMA_CUBE = EntityType.MAGMA_CUBE;
		MANGROVE_BOAT = EntityType.MANGROVE_BOAT;
		MANGROVE_CHEST_BOAT = EntityType.MANGROVE_CHEST_BOAT;
		MANNEQUIN = EntityType.MANNEQUIN;
		MARKER = EntityType.MARKER;
		MINECART = EntityType.MINECART;
		MOOSHROOM = EntityType.MOOSHROOM;
		MULE = EntityType.MULE;
		NAUTILUS = EntityType.NAUTILUS;
		OAK_BOAT = EntityType.OAK_BOAT;
		OAK_CHEST_BOAT = EntityType.OAK_CHEST_BOAT;
		OCELOT = EntityType.OCELOT;
		OMINOUS_ITEM_SPAWNER = EntityType.OMINOUS_ITEM_SPAWNER;
		PAINTING = EntityType.PAINTING;
		PALE_OAK_BOAT = EntityType.PALE_OAK_BOAT;
		PALE_OAK_CHEST_BOAT = EntityType.PALE_OAK_CHEST_BOAT;
		PANDA = EntityType.PANDA;
		PARCHED = EntityType.PARCHED;
		PARROT = EntityType.PARROT;
		PHANTOM = EntityType.PHANTOM;
		PIG = EntityType.PIG;
		PIGLIN = EntityType.PIGLIN;
		PIGLIN_BRUTE = EntityType.PIGLIN_BRUTE;
		PILLAGER = EntityType.PILLAGER;
		POLAR_BEAR = EntityType.POLAR_BEAR;
		SPLASH_POTION = EntityType.SPLASH_POTION;
		LINGERING_POTION = EntityType.LINGERING_POTION;
		PUFFERFISH = EntityType.PUFFERFISH;
		RABBIT = EntityType.RABBIT;
		RAVAGER = EntityType.RAVAGER;
		SALMON = EntityType.SALMON;
		SHEEP = EntityType.SHEEP;
		SHULKER = EntityType.SHULKER;
		SHULKER_BULLET = EntityType.SHULKER_BULLET;
		SILVERFISH = EntityType.SILVERFISH;
		SKELETON = EntityType.SKELETON;
		SKELETON_HORSE = EntityType.SKELETON_HORSE;
		SLIME = EntityType.SLIME;
		SMALL_FIREBALL = EntityType.SMALL_FIREBALL;
		SNIFFER = EntityType.SNIFFER;
		SNOWBALL = EntityType.SNOWBALL;
		SNOW_GOLEM = EntityType.SNOW_GOLEM;
		SPAWNER_MINECART = EntityType.SPAWNER_MINECART;
		SPECTRAL_ARROW = EntityType.SPECTRAL_ARROW;
		SPIDER = EntityType.SPIDER;
		SPRUCE_BOAT = EntityType.SPRUCE_BOAT;
		SPRUCE_CHEST_BOAT = EntityType.SPRUCE_CHEST_BOAT;
		SQUID = EntityType.SQUID;
		STRAY = EntityType.STRAY;
		STRIDER = EntityType.STRIDER;
		TADPOLE = EntityType.TADPOLE;
		TEXT_DISPLAY = EntityType.TEXT_DISPLAY;
		TNT = EntityType.TNT;
		TNT_MINECART = EntityType.TNT_MINECART;
		TRADER_LLAMA = EntityType.TRADER_LLAMA;
		TRIDENT = EntityType.TRIDENT;
		TROPICAL_FISH = EntityType.TROPICAL_FISH;
		TURTLE = EntityType.TURTLE;
		VEX = EntityType.VEX;
		VILLAGER = EntityType.VILLAGER;
		VINDICATOR = EntityType.VINDICATOR;
		WANDERING_TRADER = EntityType.WANDERING_TRADER;
		WARDEN = EntityType.WARDEN;
		WIND_CHARGE = EntityType.WIND_CHARGE;
		WITCH = EntityType.WITCH;
		WITHER = EntityType.WITHER;
		WITHER_SKELETON = EntityType.WITHER_SKELETON;
		WITHER_SKULL = EntityType.WITHER_SKULL;
		WOLF = EntityType.WOLF;
		ZOGLIN = EntityType.ZOGLIN;
		ZOMBIE = EntityType.ZOMBIE;
		ZOMBIE_HORSE = EntityType.ZOMBIE_HORSE;
		ZOMBIE_NAUTILUS = EntityType.ZOMBIE_NAUTILUS;
		ZOMBIE_VILLAGER = EntityType.ZOMBIE_VILLAGER;
		ZOMBIFIED_PIGLIN = EntityType.ZOMBIFIED_PIGLIN;
		PLAYER = EntityType.PLAYER;
		FISHING_BOBBER = EntityType.FISHING_BOBBER;

		*///?} >=26.2 {
		ACACIA_BOAT = EntityTypes.ACACIA_BOAT;
		ACACIA_CHEST_BOAT = EntityTypes.ACACIA_CHEST_BOAT;
		ALLAY = EntityTypes.ALLAY;
		AREA_EFFECT_CLOUD = EntityTypes.AREA_EFFECT_CLOUD;
		ARMADILLO = EntityTypes.ARMADILLO;
		ARMOR_STAND = EntityTypes.ARMOR_STAND;
		ARROW = EntityTypes.ARROW;
		AXOLOTL = EntityTypes.AXOLOTL;
		BAMBOO_CHEST_RAFT = EntityTypes.BAMBOO_CHEST_RAFT;
		BAMBOO_RAFT = EntityTypes.BAMBOO_RAFT;
		BAT = EntityTypes.BAT;
		BEE = EntityTypes.BEE;
		BIRCH_BOAT = EntityTypes.BIRCH_BOAT;
		BIRCH_CHEST_BOAT = EntityTypes.BIRCH_CHEST_BOAT;
		BLAZE = EntityTypes.BLAZE;
		BLOCK_DISPLAY = EntityTypes.BLOCK_DISPLAY;
		BOGGED = EntityTypes.BOGGED;
		BREEZE = EntityTypes.BREEZE;
		BREEZE_WIND_CHARGE = EntityTypes.BREEZE_WIND_CHARGE;
		CAMEL = EntityTypes.CAMEL;
		CAMEL_HUSK = EntityTypes.CAMEL_HUSK;
		CAT = EntityTypes.CAT;
		CAVE_SPIDER = EntityTypes.CAVE_SPIDER;
		CHERRY_BOAT = EntityTypes.CHERRY_BOAT;
		CHERRY_CHEST_BOAT = EntityTypes.CHERRY_CHEST_BOAT;
		CHEST_MINECART = EntityTypes.CHEST_MINECART;
		CHICKEN = EntityTypes.CHICKEN;
		COD = EntityTypes.COD;
		COPPER_GOLEM = EntityTypes.COPPER_GOLEM;
		COMMAND_BLOCK_MINECART = EntityTypes.COMMAND_BLOCK_MINECART;
		COW = EntityTypes.COW;
		CREAKING = EntityTypes.CREAKING;
		CREEPER = EntityTypes.CREEPER;
		DARK_OAK_BOAT = EntityTypes.DARK_OAK_BOAT;
		DARK_OAK_CHEST_BOAT = EntityTypes.DARK_OAK_CHEST_BOAT;
		DOLPHIN = EntityTypes.DOLPHIN;
		DONKEY = EntityTypes.DONKEY;
		DRAGON_FIREBALL = EntityTypes.DRAGON_FIREBALL;
		DROWNED = EntityTypes.DROWNED;
		EGG = EntityTypes.EGG;
		ELDER_GUARDIAN = EntityTypes.ELDER_GUARDIAN;
		ENDERMAN = EntityTypes.ENDERMAN;
		ENDERMITE = EntityTypes.ENDERMITE;
		ENDER_DRAGON = EntityTypes.ENDER_DRAGON;
		ENDER_PEARL = EntityTypes.ENDER_PEARL;
		END_CRYSTAL = EntityTypes.END_CRYSTAL;
		EVOKER = EntityTypes.EVOKER;
		EVOKER_FANGS = EntityTypes.EVOKER_FANGS;
		EXPERIENCE_BOTTLE = EntityTypes.EXPERIENCE_BOTTLE;
		EXPERIENCE_ORB = EntityTypes.EXPERIENCE_ORB;
		EYE_OF_ENDER = EntityTypes.EYE_OF_ENDER;
		FALLING_BLOCK = EntityTypes.FALLING_BLOCK;
		FIREBALL = EntityTypes.FIREBALL;
		FIREWORK_ROCKET = EntityTypes.FIREWORK_ROCKET;
		FOX = EntityTypes.FOX;
		FROG = EntityTypes.FROG;
		FURNACE_MINECART = EntityTypes.FURNACE_MINECART;
		GHAST = EntityTypes.GHAST;
		HAPPY_GHAST = EntityTypes.HAPPY_GHAST;
		GIANT = EntityTypes.GIANT;
		GLOW_ITEM_FRAME = EntityTypes.GLOW_ITEM_FRAME;
		GLOW_SQUID = EntityTypes.GLOW_SQUID;
		GOAT = EntityTypes.GOAT;
		GUARDIAN = EntityTypes.GUARDIAN;
		HOGLIN = EntityTypes.HOGLIN;
		HOPPER_MINECART = EntityTypes.HOPPER_MINECART;
		HORSE = EntityTypes.HORSE;
		HUSK = EntityTypes.HUSK;
		ILLUSIONER = EntityTypes.ILLUSIONER;
		INTERACTION = EntityTypes.INTERACTION;
		IRON_GOLEM = EntityTypes.IRON_GOLEM;
		ITEM = EntityTypes.ITEM;
		ITEM_DISPLAY = EntityTypes.ITEM_DISPLAY;
		ITEM_FRAME = EntityTypes.ITEM_FRAME;
		JUNGLE_BOAT = EntityTypes.JUNGLE_BOAT;
		JUNGLE_CHEST_BOAT = EntityTypes.JUNGLE_CHEST_BOAT;
		LEASH_KNOT = EntityTypes.LEASH_KNOT;
		LIGHTNING_BOLT = EntityTypes.LIGHTNING_BOLT;
		LLAMA = EntityTypes.LLAMA;
		LLAMA_SPIT = EntityTypes.LLAMA_SPIT;
		MAGMA_CUBE = EntityTypes.MAGMA_CUBE;
		MANGROVE_BOAT = EntityTypes.MANGROVE_BOAT;
		MANGROVE_CHEST_BOAT = EntityTypes.MANGROVE_CHEST_BOAT;
		MANNEQUIN = EntityTypes.MANNEQUIN;
		MARKER = EntityTypes.MARKER;
		MINECART = EntityTypes.MINECART;
		MOOSHROOM = EntityTypes.MOOSHROOM;
		MULE = EntityTypes.MULE;
		NAUTILUS = EntityTypes.NAUTILUS;
		OAK_BOAT = EntityTypes.OAK_BOAT;
		OAK_CHEST_BOAT = EntityTypes.OAK_CHEST_BOAT;
		OCELOT = EntityTypes.OCELOT;
		OMINOUS_ITEM_SPAWNER = EntityTypes.OMINOUS_ITEM_SPAWNER;
		PAINTING = EntityTypes.PAINTING;
		PALE_OAK_BOAT = EntityTypes.PALE_OAK_BOAT;
		PALE_OAK_CHEST_BOAT = EntityTypes.PALE_OAK_CHEST_BOAT;
		PANDA = EntityTypes.PANDA;
		PARCHED = EntityTypes.PARCHED;
		PARROT = EntityTypes.PARROT;
		PHANTOM = EntityTypes.PHANTOM;
		PIG = EntityTypes.PIG;
		PIGLIN = EntityTypes.PIGLIN;
		PIGLIN_BRUTE = EntityTypes.PIGLIN_BRUTE;
		PILLAGER = EntityTypes.PILLAGER;
		POLAR_BEAR = EntityTypes.POLAR_BEAR;
		SPLASH_POTION = EntityTypes.SPLASH_POTION;
		LINGERING_POTION = EntityTypes.LINGERING_POTION;
		PUFFERFISH = EntityTypes.PUFFERFISH;
		RABBIT = EntityTypes.RABBIT;
		RAVAGER = EntityTypes.RAVAGER;
		SALMON = EntityTypes.SALMON;
		SHEEP = EntityTypes.SHEEP;
		SHULKER = EntityTypes.SHULKER;
		SHULKER_BULLET = EntityTypes.SHULKER_BULLET;
		SILVERFISH = EntityTypes.SILVERFISH;
		SKELETON = EntityTypes.SKELETON;
		SKELETON_HORSE = EntityTypes.SKELETON_HORSE;
		SLIME = EntityTypes.SLIME;
		SMALL_FIREBALL = EntityTypes.SMALL_FIREBALL;
		SNIFFER = EntityTypes.SNIFFER;
		SNOWBALL = EntityTypes.SNOWBALL;
		SNOW_GOLEM = EntityTypes.SNOW_GOLEM;
		SPAWNER_MINECART = EntityTypes.SPAWNER_MINECART;
		SPECTRAL_ARROW = EntityTypes.SPECTRAL_ARROW;
		SPIDER = EntityTypes.SPIDER;
		SPRUCE_BOAT = EntityTypes.SPRUCE_BOAT;
		SPRUCE_CHEST_BOAT = EntityTypes.SPRUCE_CHEST_BOAT;
		SQUID = EntityTypes.SQUID;
		STRAY = EntityTypes.STRAY;
		STRIDER = EntityTypes.STRIDER;
		TADPOLE = EntityTypes.TADPOLE;
		TEXT_DISPLAY = EntityTypes.TEXT_DISPLAY;
		TNT = EntityTypes.TNT;
		TNT_MINECART = EntityTypes.TNT_MINECART;
		TRADER_LLAMA = EntityTypes.TRADER_LLAMA;
		TRIDENT = EntityTypes.TRIDENT;
		TROPICAL_FISH = EntityTypes.TROPICAL_FISH;
		TURTLE = EntityTypes.TURTLE;
		VEX = EntityTypes.VEX;
		VILLAGER = EntityTypes.VILLAGER;
		VINDICATOR = EntityTypes.VINDICATOR;
		WANDERING_TRADER = EntityTypes.WANDERING_TRADER;
		WARDEN = EntityTypes.WARDEN;
		WIND_CHARGE = EntityTypes.WIND_CHARGE;
		WITCH = EntityTypes.WITCH;
		WITHER = EntityTypes.WITHER;
		WITHER_SKELETON = EntityTypes.WITHER_SKELETON;
		WITHER_SKULL = EntityTypes.WITHER_SKULL;
		WOLF = EntityTypes.WOLF;
		ZOGLIN = EntityTypes.ZOGLIN;
		ZOMBIE = EntityTypes.ZOMBIE;
		ZOMBIE_HORSE = EntityTypes.ZOMBIE_HORSE;
		ZOMBIE_NAUTILUS = EntityTypes.ZOMBIE_NAUTILUS;
		ZOMBIE_VILLAGER = EntityTypes.ZOMBIE_VILLAGER;
		ZOMBIFIED_PIGLIN = EntityTypes.ZOMBIFIED_PIGLIN;
		PLAYER = EntityTypes.PLAYER;
		FISHING_BOBBER = EntityTypes.FISHING_BOBBER;
		//?}
	}
}
